## `Computer Vision`

In [2]:
#importing few libraries
import cv2
import numpy as np

In [6]:
#Reading Image

img = cv2.imread('Image/two.png', 0)
print(img)

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [56  0  0 ...  0  0  0]
 [30  0  0 ...  0  0  0]
 [ 4  0  0 ...  0  0  0]]


In [7]:
img.shape

(287, 192)

###  Display Image


In [31]:

img2 = cv2.imread('Image/TG2.jpg', 0)

img2_window = cv2.imshow('ImageWindow',img2)

cv2.waitKey(0) #image will there untill and unless any other key is pressed

#make sure to add last line if waitKey is zero

cv2.destroyAllWindows() #Destroy window

In [32]:
print(f"Data Type of the Image is {img.dtype}")
print(f"Dimension of the Image is {img.ndim}")

Data Type of the Image is uint8
Dimension of the Image is 2


### Access Pixel values & Change Pixel Value

In [27]:
#Access Pixel Values

print(img2[300,300])

0


In [26]:
#Change Pixel Value
img2[300,300] = 0 

### Modifying Image Pixel and ROI

In [33]:
img2_copy = img2.copy() #Copy of Original Image

img2_copy[100:150,80:120] = 0 #Modification

cv2.imshow("Fixed Resizing",img2_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Resizing Image

In [39]:
img3 = cv2.imread('Image/TG2.jpg', 1)

resized_img = cv2.resize(img3,(300,300))  
#resized = cv2.resize(img,(width,height), fx=1.5, fy = 1.5)

#Display Image
cv2.imshow("Resized Image", resized_img);
cv2.waitKey(0)
cv2.destroyAllWindows()

### Change Image Size while maintaining Aspect ratio

In [41]:
height, width, channels = img3.shape

r = 300.0/ width

new_height = int(height * r)

resized = cv2.resize(img3,(300, new_height))

cv2.imshow("Aspect Ratio resize", resized);
cv2.waitKey(0)
cv2.destroyAllWindows()

### Translate

In [ ]:
height, width, channels = img3.shape
